config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/signup',                   to: 'users#new'
  post   '/signup',                   to: 'users#create'
  get    '/login',                    to: 'sessions#new'
  post   '/login',                    to: 'sessions#create'
  delete '/logout',                   to: 'sessions#destroy'
  patch  '/users/:id/edit',           to: 'users#update'
  get    '/projects/signup',          to: 'projects#new'
  post   '/projects/signup',          to: 'projects#create'
  patch  '/projects/:id/edit',        to: 'projects#update'
  get    '/works/:id/edit',           to: 'works#edit'
  patch  '/works/:id/edit',           to: 'works#update'
  get    '/works/:user_id/:date',     to: 'works#show'
  get    '/works/:user_id/:date/new', to: 'works#new'
  post   '/works/:user_id/:date/new', to: 'works#create'
  delete '/works/:id',                to: 'works#destroy'
  get    '/works/search',             to: 'works#search'
  get    '/holidays/signup',          to: 'holidays#new'
  post   '/holidays/signup',          to: 'holidays#create'
  patch  '/holidays/:id/edit',        to: 'holidays#update'
  resources :users do
    collection { post :import }
  end
  resources :projects, except: [:show] do
    collection { post :import }
  end
  resources :holidays, except: [:show] do
    collection { post :import }
  end
end

app/models/holiday.rb
class Holiday < ApplicationRecord
  default_scope -> { order(:date) }
  validates :name, presence: true, length: {maximum: 20}
  validates :date, presence: true, uniqueness: true

  scope :search, -> (search_params) do
    str_date = search_params[:year] + "-01-01"
    date = str_date.to_date
    range = date.beginning_of_year..date.end_of_year
    where(date: range)
  end

  private

    def self.update_attributes(row)
      input_params = row.to_hash.slice("name", "date")
      #pattern : yyyy/mm/dd
      pattern = /\d{4}\/\d{1,2}\/\d{1,2}/
      row["date"].match(pattern) ? input_params["date"] = row["date"].to_date : input_params["date"] = ""
      return input_params
    end

end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  include SessionsHelper

  before_action :logged_in_user
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy, :import]
  before_action :set_pull_down_list, only: [:index]

  def index
    @search_params = search_params
    @holidays = Holiday.search(@search_params) unless search_params_is_empty?
  end

  def new
    @holiday = Holiday.new
  end

  def create
    @holiday = Holiday.new(holidays_params)
    if @holiday.save
      flash[:success] = "休日を登録しました。"
      redirect_to holidays_url
    else
      render 'new'
    end
  end

  def edit
    @holiday = Holiday.find_by(id: params[:id])
  end

  def update
    @holiday = Holiday.find_by(id: params[:id])
    if @holiday.update_attributes(holidays_params)
      flash[:success] = "登録内容を変更しました。"
      redirect_to holidays_url
    else
      render 'edit'
    end
  end

  def destroy
    holiday = Holiday.find_by(id: params[:id])
    unless holiday.nil?
      holiday.destroy
      flash[:success] = "登録内容を削除しました。"
    end
    redirect_to holidays_url
  end

  def import
    load_csv(Holiday, holidays_url, holidays_signup_url, ["name", "date"])
  end


  private

    def holidays_params
      params.require(:holiday).permit(:name, :date)
    end

    def search_params
      params.fetch(:search, {}).permit(:year)
    end

    def search_params_is_empty?
      return true if @search_params.blank?
      @search_params[:year].blank? ? true : false
    end

    #beforeアクション
    def set_pull_down_list
      @years = []
      year = Time.zone.now.year
      (-3..1).each do |diff|
        y = year + diff
        @years.push([y.to_s+"年", y.to_s])
      end
    end

end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_holiday_info_input_form.html.erb
<%= form_for(@holiday, url: url) do |f| %>
  <%= render 'shared/error_messages', { input: @holiday } %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :date %>
  <%= f.date_field :date, class: 'form-control' %>

  <%= f.submit btn_comment, class: "btn btn-primary" %>
<% end %>

app/views/holidays/_search_result.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">日付</th>
      <th scope="col">休日名</th>
      <% if current_user.admin? %>
        <th scope="col">編集</th>
        <th scope="col">削除</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @holidays.each do |holiday| %>
     <tr>
       <td><%= holiday.date %></td>
       <td><%= holiday.name %></td>
       <% if current_user.admin? %>
         <td><%= link_to "編集", edit_holiday_path(holiday) %></td>
         <td><%= link_to "削除", holiday, method: :delete, data: { confirm: "削除しますか？"} %></td>
       <% end %>
     </tr>
    <% end %>
  </tbody>
</table>

app/views/holidays/edit.html.erb
<% provide(:title, '登録内容の編集') %>
<h1>登録内容の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'holiday_info_input_form', { url: edit_holiday_path(@holiday), btn_comment: "保存" } %>
  </div>
</div>

app/views/holidays/index.html.erb
<% provide(:title, '休日一覧') %>
<h1>休日一覧</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 search_holidays">
    <%= form_with(scope: :search, url: holidays_path, method: :get, local: true) do |f| %>

      <%= f.hidden_field :searching, value: true %>

      <span class="work_time"><%= "対象年 : "%></span>
      <%= f.select :year, @years, {include_blank: "選択して下さい"}, class: "form_date_select" %>

      <%= f.submit "検索", class: "btn btn-primary form_date_select" %>
    <% end %>
  </div>
</div>

<% unless @holidays.blank? %>
  <h2>検索結果</h2>
  <%= render 'search_result' %>
<% end %>

app/views/holidays/new.html.erb
<% provide(:title, '休日登録') %>
<h1>休日登録</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'holiday_info_input_form', { url: holidays_signup_path, btn_comment: "登録" } %>

    <%= render 'shared/load_csv', { url: import_holidays_path,
                                    example_image: "holidays_csv_example.PNG",
                                    size: "200x100" } %>

  </div>
</div>