config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/signup',                   to: 'users#new'
  post   '/signup',                   to: 'users#create'
  get    '/login',                    to: 'sessions#new'
  post   '/login',                    to: 'sessions#create'
  delete '/logout',                   to: 'sessions#destroy'
  patch  '/users/:id/edit',           to: 'users#update'
  get    '/projects/signup',          to: 'projects#new'
  post   '/projects/signup',          to: 'projects#create'
  patch  '/projects/:id/edit',        to: 'projects#update'
  get    '/works/:id/edit',           to: 'works#edit'
  patch  '/works/:id/edit',           to: 'works#update'
  get    '/works/:user_id/:date',     to: 'works#show'
  get    '/works/:user_id/:date/new', to: 'works#new'
  post   '/works/:user_id/:date/new', to: 'works#create'
  delete '/works/:id',                to: 'works#destroy'
  get    '/works/search',             to: 'works#search'
  get    '/holidays/signup',          to: 'holidays#new'
  post   '/holidays/signup',          to: 'holidays#create'
  patch  '/holidays/:id/edit',        to: 'holidays#update'
  resources :users do
    collection { post :import }
  end
  resources :projects, except: [:show] do
    collection { post :import }
  end
  resources :holidays, except: [:show] do
    collection { post :import }
  end
end

app/views/shared/_admin_menue.html.erb
<li><%= link_to "ユーザー一覧",           users_path %></li>
<li><%= link_to "ユーザー登録",           signup_path %></li>
<li><%= link_to "プロジェクトコード一覧", projects_path %></li>
<li><%= link_to "プロジェクトコード登録", projects_signup_path %></li>
<li><%= link_to "休日一覧",               holidays_path %></li>
<li><%= link_to "休日登録",               holidays_signup_path %></li>
<li><%= link_to "工数抽出",               works_search_path %></li>
<li><%= link_to "設定の変更",             edit_user_path(current_user) %></li>

app/views/shared/_error_messages.html.erb
<% if input.errors.any? || !flash[:new_password_not_presence].nil? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      入力情報には
        <%= flash[:new_password_not_presence].nil? ? input.errors.count : input.errors.count + 1 %>
      個のエラーがあります。
    </div>
    <ul>
      <% input.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      <% unless flash[:new_password_not_presence].nil? %>
        <li><%= flash[:new_password_not_presence] %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_load_csv.html.erb
<div class="csv_import_form">
  <%= form_with( url: url, multipart: true, local: true ) do |f| %>
    <%= f.label :file, "csvから読み込む(ファイルは下の例のように記入してください。)" %>
    <br><%= image_tag example_image, size: size %>
    <%= f.file_field :file, accept: '.csv', class: 'form-control' %>
    <%= f.submit "読み込み", class: "btn btn-primary" %>
  <% end %>
</div>