config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/signup',                   to: 'users#new'
  post   '/signup',                   to: 'users#create'
  get    '/login',                    to: 'sessions#new'
  post   '/login',                    to: 'sessions#create'
  delete '/logout',                   to: 'sessions#destroy'
  patch  '/users/:id/edit',           to: 'users#update'
  get    '/projects/signup',          to: 'projects#new'
  post   '/projects/signup',          to: 'projects#create'
  patch  '/projects/:id/edit',        to: 'projects#update'
  get    '/works/:id/edit',           to: 'works#edit'
  patch  '/works/:id/edit',           to: 'works#update'
  get    '/works/:user_id/:date',     to: 'works#show'
  get    '/works/:user_id/:date/new', to: 'works#new'
  post   '/works/:user_id/:date/new', to: 'works#create'
  delete '/works/:id',                to: 'works#destroy'
  get    '/works/search',             to: 'works#search'
  get    '/holidays/signup',          to: 'holidays#new'
  post   '/holidays/signup',          to: 'holidays#create'
  patch  '/holidays/:id/edit',        to: 'holidays#update'
  resources :users do
    collection { post :import }
  end
  resources :projects, except: [:show] do
    collection { post :import }
  end
  resources :holidays, except: [:show] do
    collection { post :import }
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :works

  default_scope -> { order(:code) }
  validates :name, presence: true, length: {maximum: 30}, uniqueness: true
  validates :code, presence: true, length: {maximum: 30}, uniqueness: true

  private

    def self.update_attributes(row)
      row.to_hash.slice("name", "code")
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include SessionsHelper

  before_action :logged_in_user
  before_action :admin_user

  def index
    @projects = Project.paginate(page: params[:page])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(name: params[:project][:name], code: params[:project][:code])
    if @project.save
      flash[:success] = "プロジェクトコードを登録しました。"
      redirect_to projects_url
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find_by(id: params[:id])
  end

  def update
    @project = Project.find_by(id: params[:id])
    if @project.update_attributes(project_params_update)
      flash[:success] = "プロジェクトコードを変更しました。"
      redirect_to projects_url
    else
      render 'edit'
    end
  end

  def destroy
    project = Project.find_by(id: params[:id])
    unless project.nil?
      project.destroy
      flash[:success] = "プロジェクトを削除しました。"
    end
    redirect_to projects_url
  end

  def import
    load_csv(Project, projects_url, projects_signup_url, ["name", "code"])
  end

  private

    def project_params_update
      params.require(:project).permit(:code)
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project_info_input_form.html.erb
<%= form_for(@project, url: url) do |f| %>
  <%= render 'shared/error_messages', { input: @project } %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control', readonly: project_name_is_read_only %>

  <%= f.label :code %>
  <%= f.text_field :code, class: 'form-control' %>

  <%= f.submit btn_comment, class: "btn btn-primary" %>
<% end %>

app/views/projects/edit.html.erb
<% provide(:title, 'プロジェクトコード編集') %>
<h1>プロジェクトコード編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'project_info_input_form', { url: edit_project_path(@project), btn_comment: "保存", project_name_is_read_only: true } %>
  </div>
</div>

app/views/projects/index.html.erb
<% provide(:title, 'プロジェクトコード一覧') %>
<h1>プロジェクトコード一覧</h1>

<%= will_paginate %>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">プロジェクト名</th>
      <th scope="col">プロジェクトコード</th>
      <th scope="col">編集</th>
      <th scope="col">削除</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
     <tr>
       <td><%= project.name %></td>
       <td><%= project.code %></td>
       <td><%= link_to "編集", edit_project_path(project) %></td>
       <td><%= link_to "削除", project, method: :delete, data: { confirm: "削除しますか？"} %></td>
     </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>

app/views/projects/new.html.erb
<% provide(:title, 'プロジェクトコード登録') %>
<h1>プロジェクトコード登録</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'project_info_input_form', { url: projects_signup_path, btn_comment: "登録", project_name_is_read_only: false } %>

    <%= render 'shared/load_csv', { url: import_projects_path,
                                    example_image: "projects_csv_example.PNG",
                                    size: "200x100" } %>

  </div>
</div>