config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/signup',                   to: 'users#new'
  post   '/signup',                   to: 'users#create'
  get    '/login',                    to: 'sessions#new'
  post   '/login',                    to: 'sessions#create'
  delete '/logout',                   to: 'sessions#destroy'
  patch  '/users/:id/edit',           to: 'users#update'
  get    '/projects/signup',          to: 'projects#new'
  post   '/projects/signup',          to: 'projects#create'
  patch  '/projects/:id/edit',        to: 'projects#update'
  get    '/works/:id/edit',           to: 'works#edit'
  patch  '/works/:id/edit',           to: 'works#update'
  get    '/works/:user_id/:date',     to: 'works#show'
  get    '/works/:user_id/:date/new', to: 'works#new'
  post   '/works/:user_id/:date/new', to: 'works#create'
  delete '/works/:id',                to: 'works#destroy'
  get    '/works/search',             to: 'works#search'
  get    '/holidays/signup',          to: 'holidays#new'
  post   '/holidays/signup',          to: 'holidays#create'
  patch  '/holidays/:id/edit',        to: 'holidays#update'
  resources :users do
    collection { post :import }
  end
  resources :projects, except: [:show] do
    collection { post :import }
  end
  resources :holidays, except: [:show] do
    collection { post :import }
  end
end

app/views/layouts/_admin_dropdown.html.erb
<ul class="dropdown-menu">
  <%= render 'shared/admin_menue' %>
  <li class="divider"></li>
  <li>
    <%= link_to "ログアウト", logout_path, method: :delete %>
  </li>
</ul>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if logged_in? %>
      <%= link_to "ASMobi:工数管理システム", current_user, id: "logo" %>
    <% else %>
      <%= link_to "ASMobi:工数管理システム", root_path, id: "logo" %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to current_user.name, current_user %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              メニュー <b class="caret"></b>
            </a>
            <% if current_user.admin? %>
              <%= render 'layouts/admin_dropdown' %>
            <% else %>
              <%= render 'layouts/nonadmin_dropdown' %>
            <% end %>
          </li>
        <% else %>
          <li><%= link_to "ホーム",   root_path %></li>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_nonadmin_dropdown.html.erb
<ul class="dropdown-menu">
  <li><%= link_to "カレンダー",       current_user %></li>
  <li><%= link_to "休日一覧",         holidays_path %></li>
  <li><%= link_to "パスワードの変更", edit_user_path(current_user) %></li>
  <li class="divider"></li>
  <li>
    <%= link_to "ログアウト", logout_path, method: :delete %>
  </li>
</ul>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <% unless message_type == "new_password_not_presence" %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>